/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.*; //imports necessary components
/**
 * File Name: EmployeeRecords
 * Author: Leo Yang
 * Date: April 20, 2023
 * Description: A program that takes and manages names and personal information 
 * in and allows for viewing said information at a later date
 */
public class EmployeeRecords extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeRecords
     */
    public EmployeeRecords() {
        initComponents();
    }
    //Creates hashtables for each field
    Hashtable <String, String> hashFirstName = new Hashtable <>(); 
    Hashtable <String, String> hashLastName = new Hashtable <>();
    Hashtable <String, String> hashSalary = new Hashtable <>();
    Hashtable <String, String> hashDate = new Hashtable <>();
    Hashtable <String, String> hashGender = new Hashtable <>();
    
    ArrayList <employees> employeeAttributes= new ArrayList<>(); //creates array for employee attributes
    ArrayList <String> ids = new ArrayList <>(); //Creates array to keep track of key/ids
    //Creates an object class for employees for array
    class employees{
        String id, firstName, lastName, salary, date, gender; //creates variables
        employees (String strID, String strFirstName, String strLastName, String strSalary, String strDate, String strGender){//template for array
            id=strID;
            firstName=strFirstName;
            lastName=strLastName;
            salary=strSalary;
            date=strDate;
            gender=strGender;
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JLabel();
        txtSalary = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        inID = new javax.swing.JTextField();
        inFirstName = new javax.swing.JTextField();
        inLastName = new javax.swing.JTextField();
        inSalary = new javax.swing.JTextField();
        inDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        txtGender = new javax.swing.JLabel();
        inGender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitle.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        txtTitle.setText("Employee Records");

        txtID.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        txtID.setText("ID#:");

        txtFirstName.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        txtFirstName.setText("First Name:");

        txtLastName.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        txtLastName.setText("Last Name:");

        txtSalary.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        txtSalary.setText("Annual Salary:");

        txtDate.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        txtDate.setText("Start Date (MMDDYYYY):");

        inID.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        inFirstName.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        inLastName.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        inSalary.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        inDate.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnAdd.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(255, 204, 204));
        btnRemove.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnList.setBackground(new java.awt.Color(255, 255, 204));
        btnList.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        txtDisplay.setEditable(false);
        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane2.setViewportView(txtDisplay);

        txtGender.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        txtGender.setText("Gender:");

        inGender.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTitle)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inGender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSalary)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID)
                            .addComponent(inID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName)
                            .addComponent(inFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName)
                            .addComponent(inLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalary)
                            .addComponent(inSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate)
                            .addComponent(inDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender)
                    .addComponent(inGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        //txtDisplay.setText("");//Clears field in case of prior input
        //employeeAttributes.clear();//Clears array for employee attributes
        employees e;//Creates e variable to store employees information
        
        for (int x=0; x < ids.size(); x++){ //For loop for entire ids array
            e = new employees(ids.get(x), hashFirstName.get(ids.get(x)), hashLastName.get(ids.get(x)), hashSalary.get(ids.get(x)), hashDate.get(ids.get(x)), hashGender.get(ids.get(x))); //Adds the attributes into the variable e
            employeeAttributes.add(e);
        }
        
        
        String out = ""; //Sets up a new string for output        
        for (int y=0; y<=employeeAttributes.size()-1; y++) { //for loop for attributes array
                    out = out + employeeAttributes.get(y).firstName + " "  //obtaining attributes from arrays and adding to string
                    + employeeAttributes.get(y).lastName + " (ID#: "
                    + employeeAttributes.get(y).id + ") \nAnnual Salary: "
                    + employeeAttributes.get(y).salary + " $CAD \nGender:  "
                    + employeeAttributes.get(y).gender + "\nDate Joined: "
                    + employeeAttributes.get(y).date + "\n\n";
        }
        txtDisplay.setText(out);//print output
        
    }//GEN-LAST:event_btnListActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtDisplay.setText(""); //Clears the text display
        String id, firstName, lastName, salary, date, gender; //Sets up each of the variables 

        id = inID.getText(); //Gets the texts from the id text field and stores it into the variable id 
        firstName = inFirstName.getText(); 
        lastName = inLastName.getText();
        salary = inSalary.getText();
        date = inDate.getText();
        gender = inGender.getText();
        
        txtDisplay.append("ID#" + id + " added!\n"); //Confirmation Message
        
        hashFirstName.put(id, firstName); //Add the firstName to the hashtable, using the id as the key to reference it later on
        hashLastName.put(id, lastName);
        hashSalary.put(id,salary);
        hashDate.put(id, date);
        hashGender.put(id, gender);
        
        ids.add(id); //adds ids
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText(""); //Clears the text display
        String id; //Sets up the string ID 
        id = inID.getText(); //Gets the text in the id text field and stores it into the id variable 
        txtDisplay.append("ID#" + id + " removed!\n"); //Confirmation
        
        hashFirstName.remove(id); //removes different values from id
        hashLastName.remove(id);
        hashSalary.remove(id);
        hashDate.remove(id);
        hashGender.remove(id);
        
        ids.remove(new String(id)); //removes id                                          
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EmployeeRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnRemove;
    private javax.swing.JTextField inDate;
    private javax.swing.JTextField inFirstName;
    private javax.swing.JTextField inGender;
    private javax.swing.JTextField inID;
    private javax.swing.JTextField inLastName;
    private javax.swing.JTextField inSalary;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JLabel txtFirstName;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtLastName;
    private javax.swing.JLabel txtSalary;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
